name: Publish to NPM

on:
  push:
    paths:
      - "cdk/package.json"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install CDK Dependencies
        working-directory: cdk
        run: yarn install

      - name: Build CDK package
        working-directory: cdk
        run: yarn run build

      - name: Publish CDK package on NPM
        working-directory: cdk
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
