name: Publish to NPM

on:
  push:
    paths:
      - "pulumi/aws/package.json"
      - ".github/workflows/pulumi-aws-publish.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.4.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install Pulumi AWS Dependencies
        working-directory: pulumi/aws
        run: yarn install

      - name: Build Pulumi AWS package
        working-directory: pulumi/aws
        run: yarn run build

      - name: Publish Pulumi AWS package on NPM
        working-directory: pulumi/aws
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
